services:
  zombieland-db:
    image: postgres:latest
    container_name: zombieland-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - zombieland:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  zombieland-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    container_name: zombieland-api
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - PORT=3000
      - LOG_HTTP_HOST=zombieland-log-service
      - LOGSTASH_PORT=4005
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL_B=${ADMIN_EMAIL_B}
      - ADMIN_PASSWORD_B=${ADMIN_PASSWORD_B}
      - ADMIN_EMAIL_C=${ADMIN_EMAIL_C}
      - ADMIN_PASSWORD_C=${ADMIN_PASSWORD_C}
      - ADMIN_EMAIL_D=${ADMIN_EMAIL_D}
      - ADMIN_PASSWORD_D=${ADMIN_PASSWORD_D}
    depends_on:
      zombieland-db:
        condition: service_healthy
    restart: unless-stopped
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      zombieland-db:
        condition: service_healthy
  # mailpit:
  #   image: axllent/mailpit
  #   restart: unless-stopped
  #   ports:
  #     - "${MAILPIT_LOCAL_PORT}:8025" # Web UI
  #     - "${SMTP_LOCAL_PORT}:1025" # SMTP !

volumes:
  zombieland:

# connecter le micro-service logs au network

networks:
  default:
    name: zombieland-net
