name: Deploy API ZombieLand

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: CI
    steps:
      # Récupérer le code du dépôt dans le runner (action officiel)
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      # Prisma client pour environnement du runner
      - name: Generate Prisma Client
        run: npm run db:generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Tests unitaires
      - name: Run unit tests
        run: npm run test:unit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Tests d'intégration
      - name: Run integration tests
        run: npm run  ghact:test:spec
        env:
          HUSKY: 0
          PORT: ${{ vars.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: test
          SALT_ROUNDS: ${{ vars.SALT_ROUNDS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

  deploy:
    if: github.event_name == 'push'
    needs: run_tests
    runs-on: ubuntu-latest
    environment: CD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

			- name: Write .env file
				run: |
					ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
						${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
					cd /var/www/html/zombieland-back
					cat > .env << 'EOL'
					PORT=${{ secrets.PORT }}
					JWT_SECRET=${{ secrets.JWT_SECRET }}
					ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}
					FRONT_URL=${{ vars.FRONT_URL }}
					BACK_URL=${{ vars.BACK_URL }}
					NODE_ENV=production
					SALT_ROUNDS=${{ vars.SALT_ROUNDS }}
					DATABASE_URL=${{ secrets.DATABASE_URL }}
					DATABASE_URL_DOCKER=${{ secrets.DATABASE_URL_DOCKER }}
					POSTGRES_USER=${{ secrets.POSTGRES_USER }}
					POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
					POSTGRES_DB=${{ secrets.POSTGRES_DB }}
					EMAIL_HOST=${{ secrets.EMAIL_HOST }}
					EMAIL_PORT=587
					FROM_EMAIL=aurelien.genois@gmail.com
					EMAIL_PASS=${{ secrets.EMAIL_PASS }}
					TO_ADMIN_EMAIL=aurelien.genois@gmail.com
					SSL_DOMAIN=${{ vars.SSL_DOMAIN }}
					STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
					STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
					ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
					ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
					HUSKY=0
					EOL
					EOF


      - name: Deploy to server
        run: |
          rsync -avz --delete \
            --exclude='.env' \
            -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/zombieland-back
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            cd /var/www/html/zombieland-back
            export NODE_ENV=production
            docker-compose pull
            docker-compose -f docker-compose.prod.yml up -d --build
          EOF
