name: Run unit & integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      # Récupérer le code du dépôt dans le runner (action officiel)
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      # Prisma client pour environnement du runner
      - name: Generate Prisma Client
        run: npm run db:generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Tests unitaires
      - name: Run unit tests
        run: npm run test:unit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Tests d'intégration
      - name: Run integration tests
        run: npm run ghact:test:spec
        env:
          HUSKY: 0
          PORT: ${{ vars.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: test
          SALT_ROUNDS: ${{ vars.SALT_ROUNDS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
